שתשתÿ<†ÿ<†ÿ<†ÿ<†ÿ<†ÿ<†ÿ<†ÿ<†ÿ<†
logf:	dc.l	0	;chksum (summa=0)
	dc.l	0	;spelade matcher
	dc.l	0	;spelad tid (frames)
	dc.l	0	;skjutna skott
	dc.l	0	;antal ggr startat
	dc.l	0,0,0,0,0	;framtida anv
	dc.l	1	;antal rekord

rekord:
	dc.w	1234	;rekord fצr bana,id: 1234
	dc.w	1000,1000,1000	;lap 1,2,3	(bהst total)
	dc.b	'Rekordhוllare',0,0,0,0,0,0,0
	dc.w	1000	;bהst lap
	dc.b	'Rekordhוllare',0,0,0,0,0,0,0
SLUT:
